In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# NumPy's main object is the homogenous multidimensional array. It is a table of elements (usually numbers), all of the same
# type, indexed by a tuple of positive integers.
# In NumPy, the dimensions are called axes. For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. 
# That axis has 3 elements in it, so we say it has a length of 3. 
# NumPy’s array class is called ndarray.

In [12]:
# Basic Attributes of ndarray object
a = np.array([[1,2,3,4],[5,6,7,8]])

# ndim - Number of axes/dimensions
print(a.ndim)

# shape - Returns axes and length of axes (number of rows and columns) as a tuple of integers
print(a.shape)

# size - Total Number of elements in the array
print(a.size)

# dtype - Data Type of the elements
print(a.dtype)

# itemsize - size in bytes of each element in array
print(a.itemsize)

2
(2, 4)
8
int32
4


In [21]:
# Array Creation
# 1-d array from a single list
b = np.array([1,2,3,4])
print(b)

# n-dimensional array from a sequence of lists
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)

# Arrays with complex numbers
d = np.array([[1,2],[3,4]],dtype = complex)
print(d)

# n-dimensional arrays with standard placeholders
print(np.zeros((3,4)))
print(np.ones((3,4)))
print(np.empty((3,4))) # Junk values
print(np.eye(3,4))

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [36]:
# Generate a sequence of numbers
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,21,2))
print(np.arange(0,1,0.1))

## linspace - generate evenly spaced numbers over a specified interval (default number of samples is 50)
print(np.linspace(1,10,num = 10))
## geomspace - generate evenly spaced numbers on a log scale over a specified interval (default number of samples is 50)
print(np.geomspace(1,10,10))
plt.plot(np.arange(1,11),np.geomspace(1,10,10))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


In [65]:
# Generate random numbers and sequences
## Generate an array of random integers between two numbers
print(np.random.randint(low = 1, high = 10, size = 5))
## Generate a random sample from the given array (replacement and probabilities as additional arguments)
print(np.random.choice(b, size = 5, replace = True, p = [0.1,0.4,0.2,0.3]))
## Generate an array of random numbers with given shape (default is 1X1) between 0 and 1 from a uniform distribution 
print(np.random.rand(2,3))
## Generate an array of random numbers with given shape (default is 1X1) from a standard normal distribution 
print(np.random.randn(2,3))

## Generate random numbers from statistical distributions
print(np.random.binomial(n = 10,p = 0.7,size = 4))
print(np.random.poisson(lam = 15,size = 5))  # lam = lambda
print(np.random.exponential(scale = 2,size = 3))  # scale = 1/lambda
print(np.random.normal(loc = 5,scale = 2,size = 4))  # loc = center(mean), scale = spread(sd)
print(np.random.uniform(low = 2,high = 5,size = 4))
print(np.random.standard_t(df = 10,size = 4))

[4 9 4 4 7]
[3 2 4 2 4]
[[0.80749762 0.20252423 0.31407291]
 [0.08408017 0.90839866 0.0611235 ]]
[[-0.90878526 -0.60875519  1.10895734]
 [-0.44649228 -1.17635822 -1.51772529]]
[6 8 7 6]
[18 11  9 23 15]
[0.92707025 0.79232143 0.99614775]
[4.96643191 6.44311082 2.40949157 4.08460732]
[3.90169587 2.57134497 3.17516875 2.6648339 ]
[-0.21448202 -1.35854829 -0.06912609 -0.28530531]


In [76]:
# Shuffle array
np.random.shuffle(b)
print(b)
print(np.random.permutation(10))  # Generates permutation from np.arange(10)
print(np.random.permutation(b))  # Shuffles but not inplace like shuffle
print(b)
print(np.random.permutation(a))

[1 2 4 3]
[0 7 8 9 2 5 1 4 3 6]
[3 4 1 2]
[1 2 4 3]
[[5 6 7 8]
 [1 2 3 4]]


In [90]:
# Random Generator and Seed
seed = 123
print(np.random.RandomState(seed))
np.random.seed(seed)
print(np.random.randint(1,10,5))
print(np.random.randint(1,10,5))
np.random.seed()  # Cancels the effect of seed 
print(np.random.randint(1,10,5))

[3 3 7 2 4]
[7 2 1 2 1]
[5 5 6 9 6]


In [102]:
# Arithmetic operations in ndarrays
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)
print(x-y)
print(x*y)  # Element wise multiplication of matrices
print(x**2)  # Element wise square of matrix
print(x@y)  # Matrix Dot product
print(np.dot(x,y)) # Matrix Dot product
print(x.dot(y)) # Matrix Dot product - XY
print(y.dot(x)) # Matrix Dot product - YX 
print(np.cross(x,y)) # Matrix Cross Product

print(x.sum())  # Sum of matrix
print(x.sum(axis=0))  # Column sum
print(x.sum(axis=1))  # Row sum
print(x.cumsum())
print(x.cumsum(axis=1))  # Row cumulative sum

[[9 2 4]
 [1 4 8]
 [4 9 1]]
[[5 7 5]
 [8 7 3]
 [1 1 6]]
[[ 4 -5 -1]
 [-7 -3  5]
 [ 3  8 -5]]
[[45 14 20]
 [ 8 28 24]
 [ 4  9  6]]
[[81  4 16]
 [ 1 16 64]
 [16 81  1]]
[[65 81 75]
 [45 43 65]
 [93 92 53]]
[[65 81 75]
 [45 43 65]
 [93 92 53]]
[[65 81 75]
 [45 43 65]
 [93 92 53]]
[[72 83 81]
 [91 71 91]
 [34 60 18]]
[[-18 -25  53]
 [-44  61 -25]
 [ 53 -23  -5]]
42
[14 15 13]
[15 13 14]
[ 9 11 15 16 20 28 32 41 42]
[[ 9 11 15]
 [ 1  5 13]
 [ 4 13 14]]


In [124]:
# Indexing and Iterating
print(x[1:2,1:2])
print(x[1:3])
print(x[:,1:3])
print(x[1,...])
print(x[2])

## Iterating over ndarray
for row in y:               #Iterates over rows
    print(row)

for row in y:
    for elem in row:        # To iterate over all elements
        print(elem)
        
## A better way to iterate over all elements is to flatten the ndarray
for elem in y.flat:
    print(elem)
    
## Enumeration of ndarray to access indices and elements
for ix,elem in np.ndenumerate(y):
    print(ix,elem)

[[4]]
[[1 4 8]
 [4 9 1]]
[[2 4]
 [4 8]
 [9 1]]
[1 4 8]
[4 9 1]
[5 7 5]
[8 7 3]
[1 1 6]
5
7
5
8
7
3
1
1
6
5
7
5
8
7
3
1
1
6
(0, 0) 5
(0, 1) 7
(0, 2) 5
(1, 0) 8
(1, 1) 7
(1, 2) 3
(2, 0) 1
(2, 1) 1
(2, 2) 6


In [139]:
# Array Shape Manipulations - Return modified array, does not modify inplace
a = np.random.randint(1,10,(3,4))
print(a.shape)
print(a.ravel())  # Returns the flattened array
print(a.reshape(6,2))  # Returns reshaped array - does not modify inplace
a.resize((2,6))  # Modifies shape inplace
print(a)
print(a.reshape(4,-1))  # The dimension specified as -1 is automatically calculated with the other dimension
print(a.T)  # Returns transposed array
a.resize((3,4))

(3, 4)
[7 5 1 9 8 1 7 2 8 7 4 2]
[[7 5]
 [1 9]
 [8 1]
 [7 2]
 [8 7]
 [4 2]]
[[7 5 1 9 8 1]
 [7 2 8 7 4 2]]
[[7 5 1]
 [9 8 1]
 [7 2 8]
 [7 4 2]]
[[7 7]
 [5 2]
 [1 8]
 [9 7]
 [8 4]
 [1 2]]


In [147]:
# Stacking together different arrays
print(x)
print(y)
print(np.vstack((x,y)))   # Stacks arrays vertically
print(np.hstack((x,y)))   # Stacks arrays horizontally

# r_ and c_ are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the 
# number of the axis along which to concatenate
print(np.r_[x,y])    
print(np.c_[x,y])

# column_stack stacks 1D arrays as columns in a 2D array - different from hstack and vstack
p = np.random.randint(1,10,3)
q = np.random.randint(1,10,3)
print(np.column_stack((p,q)))
print(np.hstack((p,q)))

[[9 2 4]
 [1 4 8]
 [4 9 1]]
[[5 7 5]
 [8 7 3]
 [1 1 6]]
[[9 2 4]
 [1 4 8]
 [4 9 1]
 [5 7 5]
 [8 7 3]
 [1 1 6]]
[[9 2 4 5 7 5]
 [1 4 8 8 7 3]
 [4 9 1 1 1 6]]
[[9 2 4]
 [1 4 8]
 [4 9 1]
 [5 7 5]
 [8 7 3]
 [1 1 6]]
[[9 2 4 5 7 5]
 [1 4 8 8 7 3]
 [4 9 1 1 1 6]]
[[3 5]
 [8 9]
 [2 7]]
[3 8 2 5 9 7]


In [153]:
# Views and Copies
print(a)
t = a    # No copy - t is another name for a
t.resize(2,6)
print(a)   # Changes to t are reflected in a as well

## Shallow copy - u and a share the data (or) u looks at the same data as a
## Slicing a dataframe returns a view of it
u = a.view()     
u.resize(6,2)
print(u)
print(a)        # Shape changes to u not reflected in a
u.resize(2,6)
u[0,0] = 100
print(u)
print(a)      # Element level changes are reflected in a

## Deep Copy - Completely Independent, changes in one does not affect the other
v = a.copy()
v[0,0] = 7
print(v)
print(a)

[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]
[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]
[[100   5]
 [  1   9]
 [  8   1]
 [  7   2]
 [  8   7]
 [  4   2]]
[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]
[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]
[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]
[[7 5 1 9 8 1]
 [7 2 8 7 4 2]]
[[100   5   1   9   8   1]
 [  7   2   8   7   4   2]]


In [156]:
# Linear Algebra
print(x)
print(y)


[[9 2 4]
 [1 4 8]
 [4 9 1]]
[[5 7 5]
 [8 7 3]
 [1 1 6]]


array([[65, 81, 75],
       [45, 43, 65],
       [93, 92, 53]])